"""The bank-first demo, end to end, fixture mode, desktop + 390px.
Run: BASE=http://127.0.0.1:8016 scratchpad/pw/bin/python tests/ui/walk_bank_first.py"""
import os, sys
from playwright.sync_api import sync_playwright
BASE = os.environ.get("BASE", "http://127.0.0.1:8014"); SHOTS = os.environ.get("SHOTS", "/tmp/agent-passport-shots"); os.makedirs(SHOTS, exist_ok=True)
problems, errors = [], []
def check(c, m): (print("  ✓", m) if c else (problems.append(m), print("  ✗", m)))
def low(page, sel): return page.locator(sel).inner_text().lower()
def last_line(page): return page.locator("#term-lines li:has(.t-verdict)").last
def click_beat(page, i):
    n = page.locator("#term-lines li:has(.t-verdict)").count(); page.locator("#beats button").nth(i).click()
    page.wait_for_function(f"document.querySelectorAll('#term-lines li .t-verdict').length > {n}"); page.wait_for_function("!document.querySelector('#beats button[data-running]')", timeout=60000)
BAD = ("govdemo", "gov.uk", "approved by the authority", "the authority approves", "supervisor condition", "certificate", "regulator panel")
with sync_playwright() as pw:
    b = pw.chromium.launch(); page = b.new_context(viewport={"width": 1280, "height": 900}).new_page()
    page.on("pageerror", lambda e: errors.append(str(e)))
    seed = page.request.post(BASE + "/api/demo/seed?stage=registered").json()
    print("== 1 · Provider: the product is on the register, nobody reviewed it")
    page.goto(BASE + f"/provider?ref={seed['registration']}"); page.wait_for_selector("#pv-checks tbody tr")
    check("on the register" in low(page, "#pv-status") and page.locator("#pv-checks tbody tr").count() == 6 and "f.5" in low(page, "#pv-checks"), "filed; F.1 to F.6 recorded; F.5 Independent Assurance Evidence")
    check("does not certify" in low(page, "main"), "register framing sentence")
    print("== 2 · Bank: admission decision")
    page.goto(BASE + "/bank"); page.wait_for_selector("#bk-stats li")
    check("awaits your admission decision" in low(page, "#bk-todo") and "supervisory access" in low(page, "main"), "dashboard: pending admission, supervisory access section")
    page.goto(BASE + f"/bank?ref={seed['registration']}"); page.wait_for_selector("#review > li")
    check(page.locator("#review > li").count() == 6 and "5 of 5 as expected" in low(page, "#review") and "admit with conditions" in low(page, "#review") and "the officer decides" in low(page, "#review"), "admission review assistant: six steps, sandbox 5 of 5, recommendation labelled")
    check("independent assurance evidence" in low(page, "#bk-summary") and "minimum assurance requirements" in low(page, "main"), "evidence shown; framing question")
    page.fill("#bk-officer-note", "Filing complete, evidence covers invoice payment. Admitted with the hold condition."); page.click("#btn-admit"); page.wait_for_selector("#bk-product:not([hidden])")
    check("admitted" in low(page, "#pd-status") and "ceilings" in low(page, "#pd-summary"), "product admitted to the bank's list with ceilings and hold condition")
    print("== 3 · Customer: add an AI agent and sign the mandate in the bank's app")
    page.goto(BASE + "/customer"); page.wait_for_selector("#btn-create-agent"); page.click("#btn-create-agent"); page.wait_for_selector("#cu-mandate:not([hidden])")
    check("possession proven" in low(page, "#cu-agent-kv") and "issued when you sign" in low(page, "#cu-agent-kv"), "agent record created; passport pending")
    pid = page.locator("#cu-id").inner_text()
    page.fill("#cu-per", "12000"); page.wait_for_function("document.querySelector('#cu-containment').innerText.toLowerCase().includes('outside')")
    check(page.locator("#btn-sign-mandate").is_disabled(), "over-ceiling mandate cannot be signed")
    page.fill("#cu-per", "10000"); page.wait_for_selector("#btn-sign-mandate:not([disabled])"); page.click("#btn-sign-mandate"); page.wait_for_selector("#cu-sig:not([hidden])")
    pid = page.locator("#cu-id").inner_text(); check(pid.startswith("AP-2026-"), f"passport issued at signing: {pid}")
    page.goto(BASE + f"/bank?passport={pid}"); page.wait_for_selector("#envelope section"); page.wait_for_function("document.querySelector('#envelope-stamp').innerText.includes('ALL THREE VERIFY')")
    check("signed by the bank" in low(page, "#envelope") and "signed by the customer" in low(page, "#envelope") and page.locator(".badges li").count() == 4, "three-signer envelope: bank, customer, customer")
    check(page.locator("#btn-evidence").get_attribute("href").startswith("/api/evidence/passports/"), "evidence export on the passport")
    page.screenshot(path=f"{SHOTS}/3-passport.png", full_page=True)
    print("== 4 · Action Terminal: the invoice, two worlds")
    page.goto(BASE + "/terminal"); page.wait_for_selector("#sc-play")
    check("before the standard" in low(page, "#tab-before") and "an invoice lands on your desk" in low(page, ".sc-title"), "terminal loads")
    page.click("#tab-after"); page.click("#sc-skip"); page.wait_for_function("document.querySelector('#after-verdict').classList.contains('is-on')", timeout=60000)
    check("denied" in low(page, "#after-word") and "99887766" in low(page, "#after-reason"), "after world: denied at the payee check")
    check(page.locator("#after-chk li[data-c='R.6']").get_attribute("data-state") == "fail" and page.locator("#after-chk li[data-c='R.7']").get_attribute("data-state") == "skip", "R.6 fails, R.7 never reached")
    page.screenshot(path=f"{SHOTS}/4-terminal-after.png", full_page=True)
    print("== 5 · Expert console: clean, boundary, poisoned")
    page.goto(BASE + "/terminal?console=1"); page.wait_for_selector("#invoice-buttons button"); page.locator("#invoice-buttons button").nth(0).click(); page.wait_for_selector('#invoice-outcome [data-step="d"]:not([hidden])', timeout=60000)
    v = low(page, "#inv-verdict"); check("allow" in v and "all nine checks passed" in v and "r.4 instruction signature: verified" in v, "clean invoice ALLOW with signature evidence")
    click_beat(page, 2); li = last_line(page); check(li.locator(".t-verdict").text_content() == "DENY" and "r.7" in li.text_content().lower(), "£12,000 DENY R.7")
    st = [page.locator("#gauntlet .g-cell").nth(i).get_attribute("data-state") for i in range(page.locator("#gauntlet .g-cell").count())]
    check(st == ["pass"] * 6 + ["fail", "skip", "skip"] and "not evaluated" in low(page, "#gauntlet-wrap"), f"gauntlet: six passes, R.7 fails, R.8 and R.9 never reached {st}")
    check("receipt signed by the bank" in low(page, "#g-verdict") and "→ bank console" in low(page, "#g-verdict"), "verdict cites the bank's receipt and hands the refusal to the bank console")
    page.locator("#invoice-buttons button").nth(1).click(); page.wait_for_selector('#invoice-outcome [data-step="d"]:not([hidden])', timeout=60000)
    check(page.locator("#inv-caption").inner_text() == "The AI agent read a manipulated invoice and would have paid the wrong account. The mandate stopped it.", "poisoned invoice caption")
    page.locator("#invoice-buttons button").nth(1).click(); page.wait_for_function("fetch('/api/violations').then(r => r.json()).then(j => j.violations.length >= 3)", timeout=60000); page.wait_for_function("!document.querySelector('#invoice-buttons button[disabled]')", timeout=60000)
    print("== 6 · Bank: alert, suspend, revoke; two rails refuse")
    page.goto(BASE + f"/bank?passport={pid}"); page.wait_for_selector("#bk-alert:not([hidden])"); check("alert" in low(page, "#bk-alert"), "alert banner after two poisoned runs")
    check(page.locator("#bk-violations tbody tr[data-vid]").count() >= 3, "refusals listed with reasons")
    page.fill("#bk-reason", "two redirected invoices"); page.click("#ex-actions button:has-text('Suspend')"); page.wait_for_function("document.querySelector('#ex-state').innerText.toLowerCase().includes('suspended')")
    page.click("#ex-actions button:has-text('Revoke')"); page.wait_for_function("document.querySelector('#ex-state').innerText.toLowerCase().includes('revoked')"); page.wait_for_function("document.querySelector('#rail').innerText.toLowerCase().includes('revoked on rail')")
    check(True, "revoked on the list and on the vouch rail")
    page.goto(BASE + "/terminal?console=1"); page.wait_for_selector("#beats button"); click_beat(page, 7); li = last_line(page)
    check(li.locator(".t-verdict").text_content() == "DENY" and "r.2" in li.text_content().lower() and "two rails refuse" in li.text_content().lower(), "subsequent payment DENY R.2, two rails refuse")
    print("== 7 · Evidence trail and supervisory export")
    page.goto(BASE + "/audit"); page.wait_for_function("document.getElementById('replay-note').innerText.length > 0", timeout=60000)
    check("intact" in low(page, "#au-chain") and "replayed identically" in low(page, "#replay-note") and not low(page, "#replay-note").startswith("0 of"), f"evidence trail: {page.locator('#replay-note').inner_text()}")
    ev = page.request.get(BASE + f"/api/evidence/passports/{pid}").json()
    check(ev["chain"]["ok"] and ev["register_entry"]["receipt_verified"] and ev["envelope_verification"]["admission"] and len(ev["violations"]) >= 3, "evidence bundle verifies: chain, register receipt, admission")
    print("== 8 · Language sweep and 390px")
    m = b.new_context(viewport={"width": 390, "height": 844}).new_page()
    for path in ("", "customer", f"customer?ref={pid}", "bank", f"bank?ref={seed['registration']}", f"bank?passport={pid}", "terminal", "terminal?console=1", "audit", "provider", "about"):
        m.goto(BASE + "/" + path); m.wait_for_timeout(900); w = m.evaluate("document.documentElement.scrollWidth"); check(w <= 390, f"/{path} no overflow ({w}px)")
        body = m.evaluate("document.body.innerText").lower(); bad = [k for k in BAD if k in body]; check(not bad, f"/{path} no old-model wording {bad}")
    b.close()
print("errors:", errors or "none"); print("PROBLEMS:", problems or "none")
sys.exit(1 if problems or errors else 0)
