"""The bank-first demo, end to end, fixture mode, desktop + 390px.
Run: BASE=http://127.0.0.1:8016 scratchpad/pw/bin/python tests/ui/walk_bank_first.py"""
import os, sys
from playwright.sync_api import sync_playwright
BASE = os.environ.get("BASE", "http://127.0.0.1:8014"); SHOTS = os.environ.get("SHOTS", "/tmp/agent-passport-shots"); os.makedirs(SHOTS, exist_ok=True)
problems, errors = [], []
def check(c, m): (print("  ✓", m) if c else (problems.append(m), print("  ✗", m)))
def low(page, sel): return page.locator(sel).inner_text().lower()
def last_line(page): return page.locator("#term-lines li:has(.t-verdict)").last
def click_beat(page, i):
    n = page.locator("#term-lines li:has(.t-verdict)").count(); page.locator("#beats button").nth(i).click()
    page.wait_for_function(f"document.querySelectorAll('#term-lines li .t-verdict').length > {n}"); page.wait_for_function("!document.querySelector('#beats button[data-running]')", timeout=60000)
BAD = ("govdemo", "govdemo", "approved by the authority", "the authority approves", "supervisor condition", "certificate", "regulator panel", "\u2014")
with sync_playwright() as pw:
    b = pw.chromium.launch(); page = b.new_context(viewport={"width": 1280, "height": 900}).new_page()
    page.on("pageerror", lambda e: errors.append(str(e)))
    seed = page.request.post(BASE + "/api/demo/seed?stage=registered").json()
    print("== 1 · Provider: the product is on the register, nobody reviewed it")
    page.goto(BASE + f"/provider?ref={seed['registration']}"); page.wait_for_selector("#pv-checks tbody tr")
    check("on the register" in low(page, "#pv-status") and page.locator("#pv-checks tbody tr").count() == 6 and "f.5" in low(page, "#pv-checks"), "filed; F.1 to F.6 recorded; F.5 Independent Assurance Evidence")
    check("does not certify" in low(page, "main"), "register framing sentence")
    print("== 2 · Bank: admission decision")
    page.goto(BASE + "/bank"); page.wait_for_selector("#bk-todo:not([hidden])")
    check("awaits your admission decision" in low(page, "#bk-todo") and page.locator("#bk-supervisory").count() == 1 and "transaction log" in low(page, "main") and page.locator("#bd-attention").count() == 1 and "nothing needs attention" in low(page, "#bd-attention"), "dashboard: pending admission, needs attention (empty), transaction log, supervisory access")
    page.goto(BASE + f"/bank?ref={seed['registration']}"); page.wait_for_selector("#review > li")
    check(page.locator("#review > li").count() == 6 and "5 of 5 as expected" in low(page, "#review") and "admit with conditions" in low(page, "#review") and "the officer decides" in low(page, "#review"), "admission review assistant: six steps, sandbox 5 of 5, recommendation labelled")
    check("independent assurance evidence" in low(page, "#bk-summary") and "minimum assurance requirements" in low(page, "main"), "evidence shown; framing question")
    check("independently audited" in low(page, "#bk-summary") and "scaled by the declared assurance level" in low(page, "#bk-ceilings"), "assurance level badge and level-scaled ceilings on the admission view")
    check(page.input_value("#bk-condition") == "" and page.input_value("#bk-officer-note") == "", "bank admission inputs start empty")
    page.click("#btn-admit"); page.wait_for_selector("#decide-error:not([hidden])"); check("required" in low(page, "#decide-error") or "hold condition" in low(page, "#decide-error"), "admit with empty inputs is refused inline")
    page.click("#btn-bk-prefill"); page.wait_for_selector("#bk-context:not([hidden])"); check("meridian bank" in low(page, "#bk-context") and "a. ferreira" in low(page, "#bk-context"), "bank context panel introduces the cast")
    page.click("#btn-bk-prefill-go"); check(page.input_value("#bk-condition") == "5000" and page.input_value("#bk-officer-note").strip() != "", "prefill enters the hold condition and a file note")
    page.click("#btn-admit"); page.wait_for_selector("#bk-product:not([hidden])")
    check("admitted" in low(page, "#pd-status") and "ceilings" in low(page, "#pd-summary"), "product admitted to the bank's list with ceilings and hold condition")
    print("== 3 · Customer: add an AI agent and sign the mandate in the bank's app")
    page.goto(BASE + "/customer"); page.wait_for_selector("#cu-add-toggle"); page.click("#cu-add-toggle"); page.click("#btn-create-agent"); page.wait_for_selector("#cu-mandate:not([hidden])")
    check("possession proven" in low(page, "#cu-agent-kv") and "issued when you sign" in low(page, "#cu-agent-kv") and "business current account" in low(page, "main"), "agent record created inside the account; passport pending")
    check(page.input_value("#cu-per") == "" and page.input_value("#cu-monthly") == "" and page.locator("#cu-suppliers [data-k='name']").count() == 0 and page.locator("#btn-sign-mandate").is_disabled(), "mandate form starts empty, signing disabled")
    page.click("#btn-cu-prefill"); page.wait_for_selector("#cu-context:not([hidden])"); check("northgate joinery" in low(page, "#cu-context") and "helen marsh" in low(page, "#cu-context"), "customer context panel introduces the cast")
    page.click("#btn-cu-prefill-go"); page.wait_for_function("document.querySelector('#cu-per').value === '10000'"); check(page.locator("#cu-suppliers [data-k='name']").count() == 3, "prefill fills the three suppliers and the limits")
    page.wait_for_function("document.querySelector('#cu-limits') && document.querySelector('#cu-limits').innerText.includes('payments a day')")
    check("business current account" in low(page, "#cu-limits") and "agent ceiling up to" in low(page, "#cu-limits") and "gbp only" in low(page, "#cu-limits"), "agent-channel limits from the account tier shown on the form")
    page.wait_for_function("document.querySelector('#cu-ch-0') && document.querySelector('#cu-ch-0').innerText.includes('public register')")
    check("fenwick timber ltd" in low(page, "#cu-ch-0") and "checked against the public register" in low(page, "#cu-ch-0"), "payee checked against the public register (live or labelled demo)")
    pid = page.locator("#cu-id").inner_text()
    page.click("#cu-add"); page.fill("#cu-suppliers [data-i='3'][data-k='name']", "coast"); page.wait_for_function("document.querySelector('#cu-ch-3') && document.querySelector('#cu-ch-3').innerText.toLowerCase().includes('coastline')")
    page.click("#cu-ch-3 [data-pick]"); page.wait_for_function("document.querySelector('#cu-suppliers [data-i=\"3\"][data-k=\"companies_house_number\"]').value !== ''")
    check(page.input_value("#cu-suppliers [data-i='3'][data-k='companies_house_number']") != "" and "coastline glass" in page.input_value("#cu-suppliers [data-i='3'][data-k='name']").lower() and "checked against the public register" in low(page, "#cu-ch-3"), "name first: typing the name lists register matches; picking one fills number, legal name and status")
    page.click("#cu-suppliers [data-remove='3']")
    page.fill("#cu-per", "12000"); page.wait_for_function("document.querySelector('#cu-containment').innerText.toLowerCase().includes('outside')")
    check(page.locator("#btn-sign-mandate").is_disabled(), "over-ceiling mandate cannot be signed")
    page.fill("#cu-per", "10000"); page.wait_for_selector("#btn-sign-mandate:not([disabled])"); page.click("#btn-sign-mandate"); page.wait_for_selector("#cu-sig:not([hidden])")
    pid = page.locator("#cu-id").inner_text(); check(pid.startswith("AP-2026-"), f"passport issued at signing: {pid}")
    check("checked against the public register" in low(page, "#cu-suppliers-signed") and "confirmation of payee planned" in low(page, "#cu-suppliers-signed") and "not more than 10 payments" in low(page, "#cu-kv"), "signed mandate carries the register check, velocity and currency")
    print("== 3b · Customer: amend the mandate")
    page.click("#btn-amend-mandate"); page.wait_for_selector("#cu-form:not([hidden])"); check(page.input_value("#cu-per") == "10000" and "amend the mandate (version 2)" in low(page, "#cu-form-h"), "amend opens the form prefilled with the current values")
    page.fill("#cu-per", "12000"); page.wait_for_function("document.querySelector('#cu-containment').innerText.toLowerCase().includes('outside')"); check(page.locator("#btn-sign-mandate").is_disabled(), "over-ceiling amendment refused inline")
    page.fill("#cu-per", "3000"); page.wait_for_selector("#btn-sign-mandate:not([disabled])"); page.click("#btn-sign-mandate"); page.wait_for_function("document.querySelector('#cu-sig') && document.querySelector('#cu-sig').innerText.toLowerCase().includes('version 2')")
    check("supersedes version 1" in low(page, "#cu-sig") and "previous mandate versions" in low(page, "#cu-versions"), "version 2 signed, version 1 retained")
    deny = page.request.post(BASE + "/api/agent/act", data={"passport_id": pid, "supplier_name": "Fenwick Timber Ltd", "payee_account_ref": "60-11-22 10101010", "amount": 3200, "invoice_ref": "FT-1040"}).json()
    check(deny["decision"] == "DENY" and deny["rule"] == "R.7", "the newest version is enforced immediately: £3,200 refused at R.7 under the £3,000 limit")
    page.wait_for_function("document.querySelector('#ac-audit').innerText.toLowerCase().includes('mandate amended')"); check("mandate amended" in low(page, "#ac-audit"), "amendment on the evidence trail")
    page.click("#btn-amend-mandate"); page.wait_for_selector("#cu-form:not([hidden])"); page.fill("#cu-per", "10000"); page.wait_for_selector("#btn-sign-mandate:not([disabled])"); page.click("#btn-sign-mandate"); page.wait_for_function("document.querySelector('#cu-sig') && document.querySelector('#cu-sig').innerText.toLowerCase().includes('version 3')")
    page.goto(BASE + f"/bank?passport={pid}"); page.wait_for_selector("#envelope section"); page.wait_for_function("document.querySelector('#envelope-stamp').innerText.includes('ALL THREE VERIFY')")
    check("signed by the bank" in low(page, "#envelope") and "signed by the customer" in low(page, "#envelope") and page.locator(".badges li").count() == 4, "three-signer envelope: bank, customer, customer")
    check(page.locator("#btn-evidence").get_attribute("href").startswith("/api/evidence/passports/"), "evidence export on the passport")
    page.screenshot(path=f"{SHOTS}/3-passport.png", full_page=True)
    print("== 4 · Action Terminal: the invoice, two worlds")
    page.goto(BASE + "/terminal"); page.wait_for_selector("#sc-play")
    check("before the standard" in low(page, "#tab-before") and "an invoice lands on your desk" in low(page, ".sc-title"), "terminal loads")
    page.click("#tab-after"); page.click("#sc-skip"); page.wait_for_function("document.querySelector('#after-verdict').classList.contains('is-on')", timeout=60000)
    check("denied" in low(page, "#after-word") and "99887766" in low(page, "#after-reason"), "after world: denied at the payee check")
    check(page.locator("#after-chk li[data-c='R.6']").get_attribute("data-state") == "fail" and page.locator("#after-chk li[data-c='R.7']").get_attribute("data-state") == "skip", "R.6 fails, R.7 never reached")
    page.screenshot(path=f"{SHOTS}/4-terminal-after.png", full_page=True)
    print("== 5 · Expert console: clean, boundary, poisoned")
    page.goto(BASE + "/terminal?console=1"); page.wait_for_selector("#invoice-buttons button"); page.locator("#invoice-buttons button").nth(0).click(); page.wait_for_selector('#invoice-outcome [data-step="d"]:not([hidden])', timeout=60000)
    v = low(page, "#inv-verdict"); check("allow" in v and "all nine checks passed" in v and "r.4 instruction signature: verified" in v, "clean invoice ALLOW with signature evidence")
    click_beat(page, 2); li = last_line(page); check(li.locator(".t-verdict").text_content() == "DENY" and "r.7" in li.text_content().lower(), "£12,000 DENY R.7")
    st = [page.locator("#gauntlet .g-cell").nth(i).get_attribute("data-state") for i in range(page.locator("#gauntlet .g-cell").count())]
    check(st == ["pass"] * 6 + ["fail", "skip", "skip"] and "not evaluated" in low(page, "#gauntlet-wrap"), f"gauntlet: six passes, R.7 fails, R.8 and R.9 never reached {st}")
    check("receipt signed by the bank" in low(page, "#g-verdict") and "→ bank dashboard" in low(page, "#g-verdict"), "verdict cites the bank's receipt and hands the refusal to the bank dashboard")
    click_beat(page, 8); li = last_line(page); check(li.locator(".t-verdict").text_content() == "DENY" and "currency_not_permitted" in li.text_content().lower() and "agent error" in li.text_content().lower(), "USD instruction DENY R.6 currency, classed as agent error")
    click_beat(page, 0); click_beat(page, 9); li = last_line(page); check(li.locator(".t-verdict").text_content() == "DENY" and "replay_detected" in li.text_content().lower() and "fraud indicator" in li.text_content().lower(), "replayed instruction DENY R.4 replay, classed as fraud indicator")
    page.locator("#invoice-buttons button").nth(1).click(); page.wait_for_selector('#invoice-outcome [data-step="d"]:not([hidden])', timeout=60000)
    check(page.locator("#inv-caption").inner_text() == "The AI agent read a manipulated invoice and would have paid the wrong account. The mandate stopped it.", "poisoned invoice caption")
    page.locator("#invoice-buttons button").nth(1).click(); page.wait_for_function("fetch('/api/violations').then(r => r.json()).then(j => j.violations.length >= 3)", timeout=60000); page.wait_for_function("!document.querySelector('#invoice-buttons button[disabled]')", timeout=60000)
    print("== 6 · Bank: alert, suspend, revoke; two rails refuse")
    page.goto(BASE + f"/bank?passport={pid}"); page.wait_for_selector("#bk-alert:not([hidden])"); check("alert" in low(page, "#bk-alert"), "alert banner after two poisoned runs")
    check(page.locator("#bk-violations tbody tr[data-vid]").count() >= 3, "refusals listed with reasons")
    check("fraud indicator" in low(page, "#bk-violations") and "agent error" in low(page, "#bk-violations"), "refusals carry their class, fraud indicator and agent error, with different labels")
    page.click("#ex-actions button:has-text('Suspend')"); page.wait_for_function("!document.querySelector('#ex-error').hidden")
    check("reason first" in low(page, "#ex-error"), "suspend without a reason is refused")
    page.fill("#bk-reason", "two redirected invoices"); page.click("#ex-actions button:has-text('Suspend')"); page.wait_for_function("document.querySelector('#ex-state').innerText.toLowerCase().includes('suspended')")
    page.fill("#bk-reason", "pattern confirmed with the customer"); page.click("#ex-actions button:has-text('Revoke')"); page.wait_for_selector("#ex-actions button:has-text('Confirm revoke')")
    check(True, "revoke asks for confirmation"); page.click("#ex-actions button:has-text('Confirm revoke')"); page.wait_for_function("document.querySelector('#ex-state').innerText.toLowerCase().includes('revoked')"); page.wait_for_function("document.querySelector('#rail').innerText.toLowerCase().includes('revoked on rail')")
    check(True, "revoked on the list and on the vouch rail")
    page.goto(BASE + "/terminal?console=1"); page.wait_for_selector("#beats button"); click_beat(page, 7); li = last_line(page)
    check(li.locator(".t-verdict").text_content() == "DENY" and "r.2" in li.text_content().lower() and "two rails refuse" in li.text_content().lower(), "subsequent payment DENY R.2, two rails refuse")
    print("== 7 · Evidence trail and supervisory export")
    page.goto(BASE + "/audit"); page.wait_for_function("document.getElementById('replay-note').innerText.length > 0", timeout=60000)
    check("intact" in low(page, "#au-summary") and "replayed identically" in low(page, "#replay-note") and not low(page, "#replay-note").startswith("0 of"), f"evidence trail: {page.locator('#replay-note').inner_text()}")
    ev = page.request.get(BASE + f"/api/evidence/passports/{pid}").json()
    check(ev["chain"]["ok"] and ev["register_entry"]["receipt_verified"] and ev["envelope_verification"]["admission"] and len(ev["violations"]) >= 3, "evidence bundle verifies: chain, register receipt, admission")

    # final pass: the seeded history shows both refusal classes and the replay without anyone touching the terminal
    h = page.request.post(BASE + "/api/demo/seed?stage=history").json(); check([x["decision"] for x in h["history"]] == ["ALLOW", "DENY", "DENY", "ESCALATE"], "history seed: paid, replay refused, USD refused, one held")
    page.goto(BASE + "/bank"); page.wait_for_selector("#bd-log tbody tr.bd-log__row"); log = low(page, "#bd-log")
    check("fraud indicator" in log and "agent error" in log and "replay detected" in log, "bank log: refused rows carry their class; the replay is refused with its own reason")
    att = low(page, "#bd-attention"); check(page.locator("#bd-attention-list .bd-att__row--fraud").count() >= 1 and "agent error" not in att.replace("agent error: the agent's own mistake", "") and page.locator("#bd-attention-list .bd-att__row--held").count() == 1, "needs attention: the held payment and the fraud indicator, never the agent error")
    check("fraud indicator: something the customer never authorised" in att and "legend" not in att, "legend line where classes first appear")
    tiles = low(page, "#bk-stats"); check("payments today" in tiles and "held" in tiles and "refused (fraud)" in tiles and "refused (agent error)" in tiles and "total value processed" in tiles, "summary tiles")
    check("processed" in low(page, "#bk-agents") and "held" in low(page, "#bk-agents") and "refused" in low(page, "#bk-agents"), "agent rows carry processed, held and refused counts")
    page.click("#bd-attention-list [data-decide='release']"); page.wait_for_function("document.querySelector('#bd-attention-list .bd-att__row--held') === null")
    check("released by approver" in low(page, "#bd-log") and "held payment released by approver" in page.request.get(BASE + "/api/audit").json()["rows"][0]["entry"]["event"], "approve and release: the payment moved and the chain names the decision")
    page.request.post(BASE + "/api/agent/act", data={"passport_id": h["passport_id"], "supplier_name": "Coastline Glass Ltd", "payee_account_ref": "20-13-57 77665544", "amount": 5100, "invoice_ref": "CG-0872"})
    page.reload(); page.wait_for_selector("#bd-attention-list [data-decide='refuse']"); page.click("#bd-attention-list [data-decide='refuse']"); page.wait_for_function("document.querySelector('#bd-attention-list .bd-att__row--held') === null")
    check("refused · by approver" in low(page, "#bd-log") and page.request.get(BASE + "/api/audit").json()["rows"][0]["entry"]["reason"] == "held payment refused by approver", "refuse and record: recorded equivalently")
    check("refused · fraud indicator" in low(page, "#bd-log") and "refused · agent error" in low(page, "#bd-log") and "processed" in low(page, "#bd-log"), "status column: Processed, Held decided, Refused with class")
    page.locator("#bd-log tbody tr.bd-log__row").filter(has_text="replay").first.click(); page.wait_for_selector("#bd-log .bd-detail")
    check("nonce" in low(page, "#bd-log .bd-detail") and "already spent" in low(page, "#bd-log .bd-detail"), "evidence record names the spent nonce")
    st = low(page, "#bd-stats"); check("value processed" in st and "refused, fraud indicator" in st and page.locator("#chart-volume").count() == 1 and page.locator("#bd-stats-agents tbody tr").count() >= 1 and "operational view" in st, "statistics: totals, volume chart, per-agent table, caption")
    page.click(".bd-more summary"); check("assurance level" in low(page, "#bk-register thead") and "independently audited" in low(page, "#bk-register"), "bank register table shows the assurance level")
    page.goto(BASE + "/customer"); page.wait_for_selector("#ac-audit tbody tr"); trail = low(page, "#ac-audit")
    check("refused · fraud indicator" in trail and "refused · agent error" in trail and "released by approver" in trail, "customer trail: same status chips, the human decision visible")
    check("fraud indicator: something the customer never authorised" in low(page, "#cu-legend"), "customer legend line")
    check("paid this month" in low(page, "#cu-agents") and "held" in low(page, "#cu-agents") and "refused" in low(page, "#cu-agents"), "agent card carries its quality counts")
    page.goto(BASE + f"/customer?ref={h['passport_id']}"); page.wait_for_selector("#cu-kv"); check("agent ceiling up to" in low(page, "#cu-limits") and "business current" in low(page, "#cu-limits"), "mandate form shows the account-type maximum")
    check("independently audited" in low(page, "#cu-model"), "customer product picker shows the assurance level")
    page.goto(BASE + f"/customer?ref={h['passport_id']}"); page.wait_for_selector("#btn-revoke-mandate:not([hidden])"); page.once("dialog", lambda dlg: dlg.accept()); page.click("#btn-revoke-mandate"); page.wait_for_function("document.querySelector('#cu-state').innerText.toLowerCase().includes('revoked')")
    page.wait_for_function("document.querySelector('#ac-audit').innerText.toLowerCase().includes('mandate revoked')"); check("mandate revoked" in low(page, "#cu-versions") and "mandate revoked" in low(page, "#ac-audit"), "revoke: its own chain entry, the mandate ended")
    deny = page.request.post(BASE + "/api/agent/act", data={"passport_id": h["passport_id"], "supplier_name": "Coastline Glass Ltd", "payee_account_ref": "20-13-57 77665544", "amount": 100, "invoice_ref": "CG-0899"}).json()
    check(deny["decision"] == "DENY" and deny["code"] == "MANDATE_REVOKED", "after revocation the verifier refuses at R.5 MANDATE_REVOKED")
    page.goto(BASE + "/about"); ab = low(page, "body")
    check("carries a nonce" in ab and "determinism:" in ab and "replay protection:" in ab and ab.count("planned fields") == 1, "about: nonce in the envelope, determinism and replay protection side by side, planned fields once")
    print("== 8 · Language sweep and 390px")
    m = b.new_context(viewport={"width": 390, "height": 844}).new_page()
    for path in ("", "customer", f"customer?ref={pid}", "bank", f"bank?ref={seed['registration']}", f"bank?passport={pid}", "terminal", "terminal?console=1", "audit", "provider", "about"):
        m.goto(BASE + "/" + path); m.wait_for_timeout(900); w = m.evaluate("document.documentElement.scrollWidth"); check(w <= 390, f"/{path} no overflow ({w}px)")
        body = m.evaluate("document.body.innerText").lower(); bad = [k for k in BAD if k in body]; check(not bad, f"/{path} no old-model wording {bad}")
    b.close()
print("errors:", errors or "none"); print("PROBLEMS:", problems or "none")
sys.exit(1 if problems or errors else 0)
