"""The 8-stage demo (Stage 7b excluded), fixture mode, desktop + 390px. Matches the v9 A7 sequence."""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from playwright.sync_api import sync_playwright
BASE = "http://127.0.0.1:8014"; SHOTS = "/tmp/agent-passport-shots"
problems, errors = [], []
def check(c, m): (print("  ✓", m) if c else (problems.append(m), print("  ✗", m)))
def low(page, sel): return page.locator(sel).inner_text().lower()
def last_line(page): return page.locator("#term-lines li:has(.t-verdict)").last
def click_beat(page, i):
    n = page.locator("#term-lines li:has(.t-verdict)").count(); page.locator("#beats button").nth(i).click()
    page.wait_for_function(f"document.querySelectorAll('#term-lines li .t-verdict').length > {n}"); page.wait_for_function("!document.querySelector('#beats button[data-running]')", timeout=60000)
with sync_playwright() as pw:
    b = pw.chromium.launch(); page = b.new_context(viewport={"width": 1280, "height": 900}).new_page()
    page.on("pageerror", lambda e: errors.append(str(e)))
    seed = page.request.post(BASE + "/api/demo/seed?stage=submitted").json()
    print("== Stage 1 · Standards Review Assistant")
    page.goto(BASE + "/regulator"); page.wait_for_selector("#review > li")
    check(page.locator("#review > li").count() == 6 and "5 of 5 as expected" in low(page, "#review"), "six steps, sandbox 5 of 5")
    check("approve with conditions" in low(page, "#review") and "human decision required" in low(page, "#review"), "recommendation labelled")
    check("regulatory assurance" in low(page, "main") and "phase 2" in low(page, "main") and "policy ceilings" in low(page, "main"), "Phase 2 framing and ceilings shown")
    check("m.1" in low(page, "#rg-checks") and "m.6" in low(page, "#rg-checks") and page.locator("#rg-checks .tag--amber").count() == 0, "model checks M.1 to M.6 pass")
    page.fill("#rg-officer-note", "Assistant recommends approve with conditions; I decide."); page.click("#btn-approve"); page.wait_for_selector("#rg-model:not([hidden])")
    check("approved" in low(page, "#md-status") and "policy ceilings" in low(page, "#md-summary"), "model approved with ceilings and condition; no passport yet")
    print("== Stage 2 · Issuance")
    page.goto(BASE + "/customer"); page.wait_for_selector("#btn-create-agent"); page.click("#btn-create-agent"); page.wait_for_selector("#cu-mandate:not([hidden])")
    check("possession proven" in low(page, "#cu-agent-kv") and "issued automatically" in low(page, "#cu-agent-kv"), "customer created its agent on the approved model")
    pid = page.locator("#cu-id").inner_text()
    page.goto(BASE + f"/regulator?passport={pid}"); page.wait_for_selector("#envelope section")
    check(page.locator(".badges li").count() == 4 and "credential format: w3c vc" in low(page, "#rg-issued"), "badge row and credential format label")
    check("awaiting the customer" in low(page, "#envelope") and "issued from the model approval" in low(page, "#envelope"), "mandate panel awaits the customer; assurance issued from the model approval")
    page.goto(BASE + f"/customer?ref={pid}"); page.wait_for_selector("#btn-sign-mandate:not([disabled])")
    check("phase 3" in low(page, "main") and "within the policy ceilings" in low(page, "#cu-containment"), "customer writes its mandate within the ceilings")
    page.fill("#cu-per", "12000"); page.wait_for_function("document.querySelector('#cu-containment').innerText.toLowerCase().includes('outside')")
    check(page.locator("#btn-sign-mandate").is_disabled(), "over-ceiling mandate cannot be signed")
    page.fill("#cu-per", "10000"); page.wait_for_selector("#btn-sign-mandate:not([disabled])"); page.click("#btn-sign-mandate"); page.wait_for_selector("#cu-sig:not([hidden])")
    page.goto(BASE + f"/regulator?passport={pid}"); page.wait_for_selector("#envelope section"); page.wait_for_function("document.querySelector('#envelope-stamp').innerText.includes('ALL THREE VERIFY')")
    check(True, "ALL THREE VERIFY stamp"); page.screenshot(path=f"{SHOTS}/s2-issuance.png", full_page=True)
    print("== Stage 3 · Happy path (clean invoice)")
    page.goto(BASE + "/bank"); page.wait_for_selector("#invoice-buttons button"); page.locator("#invoice-buttons button").nth(0).click(); page.wait_for_selector('#invoice-steps [data-step="d"]:not([hidden])', timeout=60000)
    v = low(page, "#inv-verdict"); check("allow" in v and "all nine checks passed" in v and "r.4 instruction signature: verified" in v, "clean invoice ALLOW with signature evidence")
    check("cryptographic delegation verifier" in low(page, "main") and "sub-10ms" in low(page, "main"), "bank framing line")
    print("== Stage 4 · Boundary £12,000")
    click_beat(page, 2); li = last_line(page); check(li.locator(".t-verdict").inner_text() == "DENY" and "r.7" in li.inner_text().lower() and "£12,000" in li.inner_text(), "£12,000 DENY R.7")
    st = [page.locator("#gauntlet .g-cell").nth(i).get_attribute("data-state") for i in range(page.locator("#gauntlet .g-cell").count())]
    check(st == ["pass"] * 6 + ["fail", "skip", "skip"] and "not evaluated" in low(page, "#gauntlet"), f"gauntlet: six passes, R.7 fails, R.8 and R.9 never reached {st}")
    check("deny" in low(page, "#g-verdict") and "per_payment_limit_exceeded" in low(page, "#g-verdict") and "receipt signed by the authority" in low(page, "#g-verdict"), "verification view: cited verdict with receipt")
    check("refusal" in low(page, "#exhaust") and "→ regulator panel" in low(page, "#exhaust") and "→ audit" in low(page, "#exhaust"), "exhaust: refusal handed to the regulator and the audit")
    page.check("#tm-full"); click_beat(page, 2)
    check(page.evaluate("getComputedStyle(document.querySelector('#gauntlet-wrap')).position") == "fixed" and "deny" in low(page, "#g-verdict"), "full-screen rendering of the same verdict")
    page.screenshot(path=f"{SHOTS}/s4-fullscreen.png"); page.keyboard.press("Escape"); page.uncheck("#tm-full")
    check(page.evaluate("getComputedStyle(document.querySelector('#gauntlet-wrap')).position") != "fixed", "Esc returns to the terminal")
    print("== Stage 5 · Vouch mirror")
    check("vouch rail" in low(page, "#strip"), "vouch rail cell on the strip")
    page.goto(BASE + "/regulator"); page.wait_for_selector("#rail"); check("interoperability with the open agent-authorisation ecosystem" in low(page, "#rg-issued"), "interoperability line")
    print("== Stage 7 · Poisoned invoice")
    page.goto(BASE + "/bank"); page.wait_for_selector("#invoice-buttons button"); page.locator("#invoice-buttons button").nth(1).click(); page.wait_for_selector('#invoice-steps [data-step="d"]:not([hidden])', timeout=60000)
    check(any("99887766" in page.locator("#inv-text mark").nth(i).inner_text() for i in range(page.locator("#inv-text mark").count())), "a. poisoned account marked in the extracted text")
    check(page.locator("#inv-instruction .wrong").count() == 1 and "99887766" in page.locator("#inv-instruction .wrong").inner_text(), "b. wrong account highlighted red")
    v = low(page, "#inv-verdict"); check("deny" in v and "r.6" in v and "payee_not_on_mandate" in v and "fatf 2025" in v, "c. DENY R.6 with FATF note")
    check(page.locator("#inv-caption").inner_text() == "The AI read a manipulated invoice and would have paid the wrong account. The mandate stopped it.", "d. verbatim caption")
    check("violation #" in v and "open" in v, "violation recorded OPEN"); page.screenshot(path=f"{SHOTS}/s7-poisoned.png", full_page=True)
    page.locator("#invoice-buttons button").nth(1).click()
    page.wait_for_function("fetch('/api/violations').then(r => r.json()).then(j => j.violations.length >= 2)", timeout=60000)
    page.wait_for_function("!document.querySelector('#invoice-buttons button[disabled]')", timeout=60000)
    print("== Stage 8 · Escalation and revocation")
    page.goto(BASE + "/regulator"); page.wait_for_selector("#rg-alert:not([hidden])"); check("supervisor alert" in low(page, "#rg-alert"), "alert banner after two poisoned runs")
    check(page.locator("#rg-violations tbody tr[data-vid]").count() >= 2, "violations in the panel")
    page.fill("#rg-reason", "two redirected invoices"); page.click("#ex-actions button:has-text('Suspend')"); page.wait_for_function("document.querySelector('#ex-state').innerText.toLowerCase().includes('suspended')")
    page.click("#ex-actions button:has-text('Revoke')"); page.wait_for_function("document.querySelector('#ex-state').innerText.toLowerCase().includes('revoked')"); page.wait_for_function("document.querySelector('#rail').innerText.toLowerCase().includes('revoked on rail')")
    check(True, "REVOKE: registry revoked, voucher revoked")
    page.goto(BASE + "/bank"); page.wait_for_selector("#beats button"); click_beat(page, 7); li = last_line(page)
    check(li.locator(".t-verdict").inner_text() == "DENY" and "r.2" in li.inner_text().lower() and "two rails refuse" in li.inner_text().lower(), "subsequent payment DENY R.2, two rails refuse")
    page.goto(BASE + "/audit"); page.wait_for_function("document.getElementById('replay-note').innerText.length > 0", timeout=60000)
    check("intact" in low(page, "#au-chain") and "replayed identically" in low(page, "#replay-note") and not low(page, "#replay-note").startswith("0 of"), f"audit: {page.locator('#replay-note').inner_text()}")
    page.goto(BASE + "/about"); a = low(page, "main")
    for k in ("what it is not", "why it matters now", "technical standards", "regulatory context", "grounds declaration layer (j.1", "jpmorgan chase", "visa tap", "r.6 and r.7"): check(k in a, f"about: {k}")
    print("== 390px")
    m = b.new_context(viewport={"width": 390, "height": 844}).new_page()
    for path in ("provider", "regulator", "customer", "bank", "audit", "about"):
        m.goto(BASE + "/" + path); m.wait_for_timeout(800); w = m.evaluate("document.documentElement.scrollWidth"); check(w <= 390, f"/{path} no overflow ({w}px)")
    b.close()
print("errors:", errors or "none"); print("PROBLEMS:", problems or "none")
sys.exit(1 if problems or errors else 0)
